### ISSUE TITLE
Issue with ValX dependency: `scikit-learn` installation.

### ISSUE THREAD

**Issue by Infinitode** [Infinitode/ValX#1]
## Issue with ValX dependency: `scikit-learn` installation.

This issue is related to the installation of **ValX**, but not caused by ValX's code.

### What happened?
Due to no prebuilt distributions for `scikit-learn`, ValX fails to install `scikit-learn` and tries to compile sklearn's package code from source. This raises an error during installation due to OpenMP compilation errors, especially on **macOS**.

### Why this happens
If you go to PYPI and look at supporting `scikit-learn` versions for your platform, prebuilt wheels are usually for lower versions of Python (3.11 and lower). They are more often than not, rather specific to your platform. This is why `pip` then tries to build from source, since no matching pre-compiled wheels were found.

### 1. Build from source
You can work from source and build, compile, and install `scikit-learn`, before installing `valx`.

> [!WARNING]
> When building from source, follow `scikit-learn's official documentation` to avoid errors during compilation.

### 2. Use a prebuilt wheel
You can change your version of Python to one supported by the `scikit-learn` version you want to use. Check which version supports the platform and the Python version you are running. You can do this by going to: https://pypi.org/project/scikit-learn/#files.

You'll notice that the filename looks something like this:
`scikit_learn-1.5.2-cp313-cp313-macosx_12_0_arm64.whl`

This filename states that this prebuilt wheel is `scikit_learn version 1.5.2` for Python `3.13` and `macOS 12.0 arm64`. 

> [!NOTE]
> There are other workarounds to resolve this issue, such as trying to disable OpenMP during the installation of `scikit-learn`, but this will disable OpenMP parallelism in `scikit-learn`.

**Comment by johanbeytell1** [comment]
**ValX 0.2.4** now includes automatic model selection based on the `scikit-learn` version you have installed. This solves compatibility issues with `scikit-learn 1.3.0` and later.

> [!IMPORTANT]
>If you are using `scikit-learn 1.3.0` or later:
> - You can keep using `numpy 2.x`.
> 
> If you are using `scikit-learn` versions older than `1.3.0`:
> - You must also downgrade your `numpy 2.x` to an older `numpy 1.x` version.
